# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 227917dbdf30b9e2b5788c2caf563f8cecbd6021098a14c254bfff64746abe7621d39c85503ff4e559f3e02889bb8dc5eef3d61557741bb1ad653943cd4e6575

test:
  secret_key_base: e22e605adc71da7023f1265da384fb55cf420017fd214e85bcfbf73324917b16fd787f968677e921aa909fe5f5482b0243394e32702cd449ce2695a183ff7345

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
